language: rust
rust:
  - stable
  - beta
  - nightly
services:
  - postgresql
env:
  TEST_DATABASE_URL=postgres://postgres@localhost:5432
script:
  - cargo test --manifest-path=tests/Cargo.toml --features="sqlite"
  - RUST_TEST_THREADS=1 cargo test --manifest-path=tests/Cargo.toml --features="postgres"
